---
title: Content Analysis of Scaling Up Nutrition (SUN) Movement Progress Reports from
  2011-2017
author: "Ernest Guevarra"
date: "17/05/2018"
output: 
  pdf_document:
    highlight: tango
    keep_tex: yes
    latex_engine: xelatex
header_includes: 
  \usepackage{float} 
  \usepackage{setspace} 
  \onehalfspacing
fontsize: 12pt
geometry: margin=2cm
classoption: a4paper
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, cache = TRUE)
options(width = 100, dplyr.width = 100)
devtools::install_github("ernestguevarra/scalingupnutrition")
library(scalingupnutrition)
library(tidyverse)
library(tidytext)
library(wordcloud)
theme_set(theme_light())
```

## Re-structure dataset into a one-token-per-row format

```{r, eval = TRUE}
tidy_reports <- progress_reports() %>%
  unnest_tokens(word, text)
  
tidy_reports
```


## Remove stop words - words not useful in analysis

```{r, eval = TRUE}
data(stop_words)

tidy_reports <- tidy_reports %>%
  anti_join(stop_words)
```


## Find the most common words in all the reports as a whole

```{r, eval = TRUE}
tidy_reports %>%
  count(word, sort = TRUE)
```

## Visualise the most common words

```{r, eval = TRUE}
tidy_reports %>%
  count(word, sort = TRUE) %>%
  filter(n > 600) %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n)) + 
  geom_col() + 
  xlab(NULL) + 
  coord_flip()
```

```{r, eval = TRUE}
nrc_joy <- get_sentiments("nrc") %>% 
  filter(sentiment == "joy")

tidy_reports %>%
  filter(year == 2011) %>%
  inner_join(nrc_joy) %>%
  count(word, sort = TRUE)
```

```{r, eval = TRUE}
progress_sentiment <- tidy_reports %>%
  inner_join(get_sentiments("bing")) %>%
  #count(year, index = linenumber %/% 80, sentiment) %>%
  count(year, index = page, sentiment) %>%
  spread(sentiment, n, fill = 0) %>%
  mutate(sentiment = positive - negative)
```

```{r, eval = TRUE, fig.height = 10}
ggplot(progress_sentiment, aes(index, sentiment, fill = year)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~year, ncol = 2, scales = "free_x")
```

```{r, eval = TRUE}
report_2011 <- tidy_reports %>% 
  filter(year == 2011)

report_2011
```

```{r, eval = TRUE}
afinn <- report_2011 %>% 
  inner_join(get_sentiments("afinn")) %>% 
  #group_by(index = linenumber %/% 80) %>%
  group_by(index = page) %>%
  summarise(sentiment = sum(score)) %>% 
  mutate(method = "AFINN")

bing_and_nrc <- bind_rows(report_2011 %>% 
                            inner_join(get_sentiments("bing")) %>%
                            mutate(method = "Bing et al."),
                          report_2011 %>% 
                            inner_join(get_sentiments("nrc") %>% 
                                         filter(sentiment %in% c("positive", 
                                                                 "negative"))) %>%
                            mutate(method = "NRC")) %>%
  #count(method, index = linenumber %/% 80, sentiment) %>%
  count(method, index = page, sentiment) %>%
  spread(sentiment, n, fill = 0) %>%
  mutate(sentiment = positive - negative)
```

```{r, eval = TRUE, fig.height = 10}
bind_rows(afinn, 
          bing_and_nrc) %>%
  ggplot(aes(index, sentiment, fill = method)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~method, ncol = 1, scales = "free_y")
```

```{r, eval = TRUE}
bing_word_counts <- tidy_reports %>%
  inner_join(get_sentiments("bing")) %>%
  count(word, sentiment, sort = TRUE) %>%
  ungroup()

bing_word_counts
```

```{r, eval = TRUE}
bing_word_counts %>%
  group_by(sentiment) %>%
  top_n(10) %>%
  ungroup() %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n, fill = sentiment)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~sentiment, scales = "free_y") +
  labs(y = "Contribution to sentiment",
       x = NULL) +
  coord_flip()
```

```{r, eval = TRUE}
library(wordcloud)

tidy_reports %>%
  anti_join(stop_words) %>%
  count(word) %>%
  with(wordcloud(word, n, max.words = 100))
```
